export namespace named_colour {
  export type NamedColour =
    | `light${""}salmon`
    | `salmon`
    | `dark${""}salmon`
    | `light${""}coral`
    | `indian${""}red`
    | `crimson`
    | `firebrick`
    | `red`
    | `dark${""}red`
    | `coral`
    | `tomato`
    | `orange${""}red`
    | `gold`
    | `orange`
    | `dark${""}orange`
    | `light${""}yellow`
    | `lemon${""}chiffon`
    | `light${""}goldenrod${""}yellow`
    | `papa${""}ya${""}whip`
    | `moccasin`
    | `peach${""}puff`
    | `pale${""}goldenrod`
    | `khaki`
    | `dark${""}khaki`
    | `yellow`
    | `lawn${""}green`
    | `chartreuse`
    | `lime${""}green`
    | `lime`
    | `forest${""}green`
    | `green`
    | `dark${""}green`
    | `green${""}yellow`
    | `yellow${""}green`
    | `spring${""}green`
    | `medium${""}spring${""}green`
    | `light${""}green`
    | `pale${""}green`
    | `dark${""}sea${""}green`
    | `medium${""}sea${""}green`
    | `sea${""}green`
    | `olive`
    | `dark${""}olive${""}green`
    | `olive${""}drab`
    | `light${""}cyan`
    | `cyan`
    | `aqua`
    | `aquamarine`
    | `medium${""}aquamarine`
    | `pale${""}turquoise`
    | `turquoise`
    | `medium${""}turquoise`
    | `dark${""}turquoise`
    | `light${""}sea${""}green`
    | `cadet${""}blue`
    | `dark${""}cyan`
    | `teal`
    | `powder${""}blue`
    | `lightblue`
    | `light${""}sky${""}blue`
    | `sky${""}blue`
    | `deep${""}sky${""}blue`
    | `light${""}steel${""}blue`
    | `dodger${""}blue`
    | `cornflower${""}blue`
    | `steel${""}blue`
    | `royal${""}blue`
    | `blue`
    | `medium${""}blue`
    | `darkblue`
    | `navy`
    | `midnight${""}blue`
    | `medium${""}slate${""}blue`
    | `slate${""}blue`
    | `dark${""}slate${""}blue`
    | `lavender`
    | `thistle`
    | `plum`
    | `violet`
    | `orchid`
    | `fuchsia`
    | `magenta`
    | `medium${""}orchid`
    | `medium${""}purple`
    | `blue${""}violet`
    | `dark${""}violet`
    | `dark${""}orchid`
    | `dark${""}magenta`
    | `purple`
    | `indigo`
    | `pink`
    | `light${""}pink`
    | `hot${""}pink`
    | `deep${""}pink`
    | `pale${""}violet${""}red`
    | `medium${""}violet${""}red`
    | `white`
    | `snow`
    | `honeydew`
    | `mint${""}cream`
    | `azure`
    | `alice${""}blue`
    | `ghost${""}white`
    | `white${""}smoke`
    | `seashell`
    | `beige`
    | `old${""}lace`
    | `floral${""}white`
    | `ivory`
    | `antique${""}white`
    | `linen`
    | `lavender${""}blush`
    | `misty${""}rose`
    | `gains${""}bo${""}ro`
    | `light${""}gray`
    | `silver`
    | `dark${""}gray`
    | `gray`
    | `dim${""}gray`
    | `light${""}slate${""}gray`
    | `slate${""}gray`
    | `dark${""}slate${""}gray`
    | `black`
    | `corn${""}silk`
    | `blanched${""}almond`
    | `bisque`
    | `navajo${""}white`
    | `wheat`
    | `burly${""}wood`
    | `tan`
    | `rosy${""}brown`
    | `sandy${""}brown`
    | `goldenrod`
    | `peru`
    | `chocolate`
    | `saddle${""}brown`
    | `sienna`
    | `brown`
    | `maroon`;
}
